# coding: utf-8

"""
    lthn API

    Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lthn_api.models.post_v1_runner_chat200_response_data import PostV1RunnerChat200ResponseData

class TestPostV1RunnerChat200ResponseData(unittest.TestCase):
    """PostV1RunnerChat200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1RunnerChat200ResponseData:
        """Test PostV1RunnerChat200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1RunnerChat200ResponseData`
        """
        model = PostV1RunnerChat200ResponseData()
        if include_optional:
            return PostV1RunnerChat200ResponseData(
                reply = ''
            )
        else:
            return PostV1RunnerChat200ResponseData(
        )
        """

    def testPostV1RunnerChat200ResponseData(self):
        """Test PostV1RunnerChat200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
