# coding: utf-8

"""
    lthn API

    Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lthn_api.models.post_v1_runner_chat200_response import PostV1RunnerChat200Response

class TestPostV1RunnerChat200Response(unittest.TestCase):
    """PostV1RunnerChat200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1RunnerChat200Response:
        """Test PostV1RunnerChat200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1RunnerChat200Response`
        """
        model = PostV1RunnerChat200Response()
        if include_optional:
            return PostV1RunnerChat200Response(
                data = lthn_api.models.post_v1_runner_chat_200_response_data.post_v1_runner_chat_200_response_data(
                    reply = '', ),
                error = lthn_api.models.error.Error(
                    code = '', 
                    details = null, 
                    message = '', ),
                meta = lthn_api.models.meta.Meta(
                    duration = '', 
                    page = 56, 
                    per_page = 56, 
                    request_id = '', 
                    total = 56, ),
                success = True
            )
        else:
            return PostV1RunnerChat200Response(
                success = True,
        )
        """

    def testPostV1RunnerChat200Response(self):
        """Test PostV1RunnerChat200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
