# coding: utf-8

"""
    lthn API

    Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lthn_api.api.runner_api import RunnerApi


class TestRunnerApi(unittest.TestCase):
    """RunnerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RunnerApi()

    def tearDown(self) -> None:
        pass

    def test_get_v1_runner_models(self) -> None:
        """Test case for get_v1_runner_models

        List configured runner model routes
        """
        pass

    def test_post_v1_runner_chat(self) -> None:
        """Test case for post_v1_runner_chat

        Multi-turn chat completion
        """
        pass

    def test_post_v1_runner_generate(self) -> None:
        """Test case for post_v1_runner_generate

        Single-prompt generation
        """
        pass


if __name__ == '__main__':
    unittest.main()
