# coding: utf-8

"""
    lthn API

    Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lthn_api.models.post_v1_runner_chat_request_messages_inner import PostV1RunnerChatRequestMessagesInner

class TestPostV1RunnerChatRequestMessagesInner(unittest.TestCase):
    """PostV1RunnerChatRequestMessagesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1RunnerChatRequestMessagesInner:
        """Test PostV1RunnerChatRequestMessagesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1RunnerChatRequestMessagesInner`
        """
        model = PostV1RunnerChatRequestMessagesInner()
        if include_optional:
            return PostV1RunnerChatRequestMessagesInner(
                content = '',
                role = ''
            )
        else:
            return PostV1RunnerChatRequestMessagesInner(
                content = '',
                role = '',
        )
        """

    def testPostV1RunnerChatRequestMessagesInner(self):
        """Test PostV1RunnerChatRequestMessagesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
