# coding: utf-8

"""
    lthn API

    Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lthn_api.models.get_v1_runner_models200_response_data import GetV1RunnerModels200ResponseData

class TestGetV1RunnerModels200ResponseData(unittest.TestCase):
    """GetV1RunnerModels200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetV1RunnerModels200ResponseData:
        """Test GetV1RunnerModels200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetV1RunnerModels200ResponseData`
        """
        model = GetV1RunnerModels200ResponseData()
        if include_optional:
            return GetV1RunnerModels200ResponseData(
                models = [
                    ''
                    ]
            )
        else:
            return GetV1RunnerModels200ResponseData(
        )
        """

    def testGetV1RunnerModels200ResponseData(self):
        """Test GetV1RunnerModels200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
